name: CI - Testing

on:
  push:
    branches:
      - main

# Specify environment variables for ALL jobs in this file to use
# env:
#   DATABASE_URL: mongodb

jobs:
  run_server_tests:
    name: Run ExpressJS App Tests
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
    # Specify environment variables for all STEPS in this job to use
    # env:
    #   DATABASE_URL: mongodb
    steps:
      # Checkout a copy of the repo contents
      - uses: actions/checkout@v4
      # Set up NodeJS in the action runner instance
      # ubuntu-latest has NodeJS v20 installed already, so we might not need actions/setup-node action?
      # NPM commands work with NodeJS v20, but we may want to customise the NodeJS version that actions use
      - uses: actions/setup-node@v4
        with:
          # Version Spec of the version to use in SemVer notation.
          # It also admits such aliases as lts/*, latest, nightly and canary builds
          # Examples: 12.x, 10.15.1, >=10.15.0, lts/Hydrogen, 16-nightly, latest, node
          node-version: 'latest'
      - name: Install dependencies
        run: npm install

      # - name: Setup MongoDB
      #   uses: supercharge/mongodb-github-action@1.12.0
      #   with:
      #     mongodb-version: 8

      - name: Run tests
        run: npm run test 
        env:
          DATABASE_URL: mongodb://localhost:27017/example-database-name
      